# .github/workflows/rspec.yml

name: RSpec

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4' # Adjust to your Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Precompile assets
        run: |
          RAILS_ENV=test bundle exec rake assets:precompile

      - name: Run RSpec
        run: |
          bundle exec rspec
          CODECLIMATE_REPO_TOKEN='6c21fcde0b6148d7b8c6d3c6fa605ff78921a22f0bd5fcff7910991d6d3a55a1' codeclimate-test-reporter
